# Generated by Django 3.2.7 on 2021-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='customphone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
